(**************************************************************)
(*      This file is distributed under the terms of the       *)
(*        Mozilla Public License Version 2.0, MPL-2.0         *)
(**************************************************************)

From Stdlib Require Import List Arith Lia Wellfounded Relations Setoid Utf8.

Import ListNotations.

Require Import utils bar ring ideal bezout noetherian.

Section principal__finitely_generated.

  Variables (𝓡 : ring).

  Add Ring 𝓡_is_ring : (is_ring 𝓡).

  Fact principal_ideal__fg_ideal : principal_ideal ⊆₁ @fg_ideal 𝓡.
  Proof.
    intros P (g & Hg); exists [g].
    intros x; rewrite Hg; split.
    + intros (? & ->); constructor 5; constructor; now left.
    + intros (u & <-)%idl_iff_lc__list%lc_inv_1; exists u; ring.
  Qed.

  (** nc stands for for non constructive *)

  Definition principal_nc := ideal ⊆₁ @principal_ideal 𝓡.
  Definition noetherian_nc := ideal ⊆₁ @fg_ideal 𝓡.

  Fact principal__noetherian_nc : principal_nc → noetherian_nc.
  Proof. intros H P HP; now apply principal_ideal__fg_ideal, H. Qed.

End principal__finitely_generated.

Section noetherian_nc_is_meaningless_constructivelly.

  (** Given any non-trivial ring (0 <> 1) discrete (ie with logically decidable 
      equality, such as eg Z or even just Z/2Z), if it is Noetherian in the 
      non-constructive sense (all ideals are finitely generated) then XM holds. *)

  Variable (𝓡 : ring).

  Add Ring 𝓡_is_ring : (is_ring 𝓡).

  Implicit Type (P : Prop) (𝓘 : 𝓡 → Prop) (x : 𝓡).

  (* The set { x | x ∼ᵣ 0ᵣ ∨ P } is an ideal *)
  Let 𝓙 P x := x ∼ᵣ 0ᵣ ∨ P.

  Local Fact 𝓙_ideal P : ideal (𝓙 P).
  Proof.
    split right.
    + intros ? ? E []; [ left | right ]; auto; now rewrite <- E.
    + now left.
    + intros ? ? [ H1 | ] [ H2 | ]; red; auto; left; rewrite H1, H2; ring.
    + intros ? ? [ H | ]; red; auto; left; rewrite H; ring.
  Qed.

  (* We assume that 𝓡 is discrete and 1ᵣ ≠ 0ᵣ
     which holds already of Z or Z/nZ (n > 1) *)

  Hypothesis (eq_dec : ∀ x y, x ∼ᵣ y ∨ ¬ x ∼ᵣ y)
             (zero_not_one : ¬ 1ᵣ ∼ᵣ @un_a 𝓡).

  Theorem finitely_gen__discriminate P : ∃𝓘, ideal 𝓘 ∧ (fg_ideal 𝓘 → P ∨ ¬ P).
  Proof.
    exists (𝓙 P); split.
    1: apply 𝓙_ideal.
    intros (l & Hl).
    (* Either l contains only 0ᵣ or some member of l is ≠ 0ᵣ *)
    destruct list_choice
      with (P := λ x, x ∼ᵣ 0ᵣ)
           (Q := λ x, ¬ x ∼ᵣ 0ᵣ)
           (l := l)
      as [ (x & H1 & H2) | H ]; auto.
    + (* If x ≠ 0ᵣ belongs to l (hence 𝓙 P), then P must hold *)
      left; cut (𝓙 P x).
      * intros []; tauto.
      * apply Hl; now constructor.
    + (* If l only contains 0ᵣ then 𝓙 P, the ideal generated by l
         is {0ᵣ} and thus P cannot hold otherwise 1ᵣ would belong to 𝓙 P *)
      assert (Hl' : ∀x, idl ⌞l⌟ x → x ∼ᵣ 0ᵣ).
      1:{ apply idl_smallest; auto.
          split right; eauto.
          * intros ? ? -> ->; ring.
          * intros ? ? ->; ring. }
      right.
      intros H1.
      apply zero_not_one, Hl', Hl; now right.
  Qed.

  Corollary noetherian_nc_implies_XM : noetherian_nc 𝓡 → ∀P, P ∨ ¬ P.
  Proof.
    intros ? P.
    destruct (finitely_gen__discriminate P) as (? & []); eauto.
  Qed.

  Corollary principal_nc_implies_XM : principal_nc 𝓡 → ∀P, P ∨ ¬ P.
  Proof. intro; now apply noetherian_nc_implies_XM, principal__noetherian_nc. Qed.

End noetherian_nc_is_meaningless_constructivelly.

Check noetherian_nc_implies_XM.
